export enum PersonalInformationSteps {
	RETAIL_CLIENT,
	INVESTMENT_CAT,
	BIO ,
	CONTACT_INFO,
	EMPLOYMENT_INFO ,
	BANK_INFO ,
    IDENTITY_PROOF,
    RISK_PROFILE,
	REVIEW 
}


export enum NextOfKinSteps
{
    BIO,
    CONTACT,
    PROOF_OF_IDENTITY,
    REVIEW
}


export enum DisclosuresSteps
{
    SIGNATURE_UPLOAD,
    BLIND_ILLITERATE,
    PEP,
    FATCA,
    KESTREL_TERMS,
    KESTREL_NOMINEE_AGREEMENT,
    AFRIVEST_EMAIL_INDEMNITY,
    DECLARATIONS,
    AFRIVEST_PRIVACY_POLICY,
    REVIEW 
}